# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  prod1:

    runs-on: ubuntu-latest
    environment: prod1

    steps:
    - uses: actions/checkout@master
      name: Checkout
    - name: Use Node.js prod1
      uses: ./.github/workflows/build/
      with:
        depl-env: ${{ secrets.AZURE_TEST }}
  prod2:

    runs-on: ubuntu-latest
    environment: prod2

    steps:
    - uses: actions/checkout@master
      name: Checkout
    - name: Use Node.js prod1
      uses: ./.github/workflows/build/
      with:
        depl-env: ${{ secrets.AZURE_TEST }}


